version: "3.9"
services:
  api-server:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - nginx
    volumes:
      - ./app:./app
    expose:
      - "5000"
    networks:
      - backend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge
