version: "3.9"
services:
  api-server:
    tty: true
    stdin_open: true
    container_name: api-server
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./app:/home/api_server/app
    expose:
      - "5000"
    networks:
      - backend

  nginx:
    tty: true
    stdin_open: true
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx:/home/nginx/
    ports:
      - "8080:80"
    networks:
      - backend
    depends_on:
      - api-server

networks:
  backend:
    driver: bridge
